logging:
  level:
    com.opentext.security.analytics.messagehub.kafkamanager: DEBUG
app:
  metrics:
    broker-jmx:
      enabled: true
      poll-interval: 30s
      targets:
        - name: broker1
          host: broker1
          port: 9101
        - name: broker2
          host: broker2
          port: 9101
        - name: broker3
          host: broker3
          port: 9101
  rate-limit:
    enabled: false
  admin:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_CONFIG:localhost:19092,localhost:29092,localhost:39092}
    security-protocol: PLAINTEXT
    default-request-timeout: 5s
    default-operation-timeout: 30s
